INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: NIT Nagaland is a National Institute of Technology located in Nagaland, India.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: The college offers B.Tech programs in CIV (Civil), MECH (Mechanical), ECE (Electronics and Communication), CSE (Computer Science), EEE (Electrical and Electronics), and EIE (Electronics and Instrumentation).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: Groups: Grp-I covers CIV, MECH, ECE and Grp-II covers CSE, EEE, EIE.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: Boys hostel Shillo-A is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: Boys hostel Shillo-B is for 4th year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: New boys hostel is for 1st year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: All boys hostels have 3-sharing rooms.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-A is for PhD and 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-B is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-C is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Boys Mess: Japfu mess serves 1st year and 3rd year boys.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Boys Mess: Sholli mess serves 2nd year, PhD, and 4th year boys.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Girls Mess: Girls mess locations: Patkai (A, B, C), Tiyi, Dzukou.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Lunch: Pakoda Sabji + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Snacks: Samosa + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Dinner: Egg Curry + Fish Curry + Banana Kopta + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Lunch: Rajma + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Snacks: Britannia Cake + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Dinner: Chicken + Seasonal Veg + Plain Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Lunch: Nutrela + Chutney + Salad + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Snacks: Kurkure + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Dinner: Egg Curry + Paneer Chole + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Breakfast: Chowmein + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Lunch: Mixed Veg (Seasonal) + Rice + Plain Dal + Salad');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Snacks: Namkeen (Aloo Bhujia / Moong Dal) + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Dinner: Kheer + Chole Bhature + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Lunch: Rajma + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Snacks: Dark Fantasy + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Dinner: Chicken Curry + Seasonal Veg + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Saturday > Lunch: Salad + Mixed Veg + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Saturday > Dinner: Egg Curry + Fish Curry + Malai Kopta + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Lunch: Rajma + Dry Pakoda + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Snacks: Kachauri + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Dinner: Chicken Bamboo Shoot + Chicken Curry + Kadhai Paneer + Sweet + Plain Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Cuisine: Mix of North Indian, non-veg heavy (chicken, fish, egg curry). Sunday dinner is the most elaborate with Chicken Bamboo Shoot (local Naga dish).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Note: This is the proposed new mess schedule.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'wifi', 'Wifi > Facts: WiFi is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'wifi', 'Wifi > Facts: LAN is also available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'attendance', 'Attendance > Facts: 75% attendance is mandatory.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Dance club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Music club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Photography club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Drawing club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fests', 'Fests > Facts: Ekarikthin is the college fest.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fests', 'Fests > Facts: Hornbill is another college fest (named after the Hornbill Festival of Nagaland).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', 'Sports > Facts: Cricket, football, volleyball, badminton, and basketball facilities are available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', 'Sports > Facts: Gym is located beside Sholli mess.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', 'Canteen > Facts: South canteen is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', 'Canteen > Facts: No restaurants near campus — only delivery services (Swiggy, Zomato) are available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'laundry', 'Laundry > Facts: No laundry facilities available on campus. Students wash clothes themselves.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: CRS (Class Representative)');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: General Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Culture Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Sports Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Finance Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant General Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Culture Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Sports Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Finance Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'medical', 'Medical > Facts: Medical facility is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'medical', 'Medical > Facts: Medical timing: 8:30 AM to 4:30 PM.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'transport', 'Transport > Facts: Nearest airport is 14 km from campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'transport', 'Transport > Facts: Nearest railway station is 19 km from campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Dzukou Valley — famous valley trek near Kohima.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Kohima War Cemetery — World War II memorial.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Kisama Heritage Village — cultural hub, hosts the Hornbill Festival.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Shopping: No shopping malls near campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Shopping: Nearby shops: Trends, Jack & Jill.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'language_climate', 'Language Climate > Languages: Hindi, English, and Naga languages are spoken.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'language_climate', 'Language Climate > Climate: Cool climate throughout the year.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester: 1st Semester');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Admission Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Grade Card: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Medical Exam Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Alumni Life Membership: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Institute Deposit Refundable: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Library Deposit Refundable: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Degree Certificate Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Convocation Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Id Card Fee: 200');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Training And Placement: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Total One Time: 14700');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Tuition Fee: 62500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Computer Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Internet Charges: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Library Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Examination Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Registration Enrolment Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Association And Cultural Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Students Aid Fee: 250');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Sports Center: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Medical And Insurance Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Total Semester: 72750');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Hostel Admission Fee: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Hostel Deposit Refundable: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Total One Time Hostel: 4000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Establishment Charges: 6000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Mess Advance Dining Charges: 21000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Hostel Seat Rent Fan Elec Water: 5000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Total Per Semester Hostel: 32000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Tuition fee is exempted for SC/ST candidates.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Most economically backward students (family income less than Rs 1 lakh per annum) get full remission of tuition fee.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Other economically backward students (family income Rs 1 lakh to Rs 5 lakh per annum) get remission of 2/3rd of tuition fee.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Dining charges are adjusted every month on per day basis calculation.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Timetable Note: B.Tech SEM-I for all branches runs from August to December 2025.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1901 Professional English');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1101 Engineering Chemistry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1102 Engineering Mathematics-I');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CS1201 Introduction to Computer Programming');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CE1201 Engineering Graphics');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1103 Engineering Chemistry Laboratory');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: ME1201 Engineering Workshop');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CS1202 Computer Programming Laboratory');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Class Timing: Classes run from 8:30 AM to 4:30 PM with breaks.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Groups: Grp-I: CIV, MECH, ECE. Grp-II: CSE, EEE, EIE.');