INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[PHOTO] Classrooms at NIT Nagaland. Interior view of NIT Nagaland classroom with desks and whiteboard');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen NIT Nagaland. Exterior or entrance view of South canteen');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior - seating area. Green-walled canteen interior with red chairs, ceiling fans, and tables');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen snack counter. Canteen snack and beverage counter with packaged food items on shelves');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior - another angle. Spacious canteen seating area with green walls, ceiling fans, and natural light from windows');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior with menu board. Canteen interior showing menu board on wall, Simply South Canteen signage visible');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen food counter with students. Students ordering at the canteen food counter with snacks and drinks display');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen counter area. Another angle of the canteen counter with students ordering food and green countertops');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] College road/pathway. Road inside NIT Nagaland campus connecting different buildings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[PHOTO] New boys hostel exterior. Exterior view of the new boys hostel building at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[PHOTO] Badminton court. Outdoor badminton court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[PHOTO] Basketball court and sports area. Open basketball court with hoop, buildings and open auditorium structure visible in background');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Parking area with mountain view. Covered parking area with cars, hills and green mountains visible in background showing NIT Nagaland''s scenic location');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - NIT Nagaland. Front view of NIT Nagaland admin block - white 3-storey building with ''National Institute of Technology Nagaland'' signage');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - close up. Close-up view of admin building showing NIT Nagaland name board, modern white building with AC units');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - wider angle. Wider angle of NIT Nagaland admin building showing the full facade');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[PHOTO] Bamboo classrooms. Unique bamboo-constructed classroom buildings at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels', '[PHOTO] Hostel building with laundry drying. White 2-storey hostel building surrounded by trees, clothes drying on balcony, hillside location');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[PHOTO] Zanibu girls hostel. Exterior view of Zanibu girls hostel at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', '[PHOTO] Girls mess. Exterior view of girls mess building at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[PHOTO] Patkai girls hostel. Exterior view of Patkai hostel for girls');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] NIT Nagaland main gate. Main entrance gate of NIT Nagaland campus');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 6s] National Institution of Nagaland admin block');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 3s] Admin block area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 7s] Campus area near admin block');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 14s] Campus walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 15s] Shilloi A and B boys hostels exterior walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', '[VIDEO 5s] Patkai A B C and Tiyi mess area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 3s] Open auditorium at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 5s] NIT Nagaland classrooms interior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 7s] Classroom/academic building area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 5s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus grounds');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus surroundings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 30s] Engineering laboratories walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 6s] Laboratory continuation');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 16s] Campus building area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[VIDEO 9s] Basketball court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[VIDEO 4s] South canteen exterior and interior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[VIDEO 3s] Canteen area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 8s] New boys hostel building walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 6s] Civil engineering department building');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 2s] Patkai A B C girls hostel exterior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 5s] Girls hostel area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 9s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[VIDEO 4s] Badminton court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 7s] Zanibu girls hostel exterior walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 9s] Road leading to South canteen');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 7s] College internal road');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 2s] Campus grounds');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 5s] Boys hostel building exterior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 18s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 27s] Campus surroundings and buildings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 2s] Campus area clip');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 15s] Road to Patkai girls hostel');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 128s] Road to South canteen - full walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 289s] Full road from college buildings to main gate');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus area');