INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: NIT Nagaland is a National Institute of Technology located in Nagaland, India.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: The college offers B.Tech programs in CIV (Civil), MECH (Mechanical), ECE (Electronics and Communication), CSE (Computer Science), EEE (Electrical and Electronics), and EIE (Electronics and Instrumentation).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'overview', 'Overview > Facts: Groups: Grp-I covers CIV, MECH, ECE and Grp-II covers CSE, EEE, EIE.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: Boys hostel Shillo-A is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: Boys hostel Shillo-B is for 4th year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: New boys hostel is for 1st year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', 'Hostels Boys > Facts: All boys hostels have 3-sharing rooms.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-A is for PhD and 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-B is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', 'Hostels Girls > Facts: Girls hostel Patkai-C is for 2nd year students, each room has 3-sharing.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Boys Mess: Japfu mess serves 1st year and 3rd year boys.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Boys Mess: Sholli mess serves 2nd year, PhD, and 4th year boys.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Girls Mess: Girls mess locations: Patkai (A, B, C), Tiyi, Dzukou.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Lunch: Pakoda Sabji + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Snacks: Samosa + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Monday > Dinner: Egg Curry + Fish Curry + Banana Kopta + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Lunch: Rajma + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Snacks: Britannia Cake + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Tuesday > Dinner: Chicken + Seasonal Veg + Plain Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Lunch: Nutrela + Chutney + Salad + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Snacks: Kurkure + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Wednesday > Dinner: Egg Curry + Paneer Chole + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Breakfast: Chowmein + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Lunch: Mixed Veg (Seasonal) + Rice + Plain Dal + Salad');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Snacks: Namkeen (Aloo Bhujia / Moong Dal) + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Thursday > Dinner: Kheer + Chole Bhature + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Lunch: Rajma + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Snacks: Dark Fantasy + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Friday > Dinner: Chicken Curry + Seasonal Veg + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Saturday > Lunch: Salad + Mixed Veg + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Saturday > Dinner: Egg Curry + Fish Curry + Malai Kopta + Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Breakfast: Bread + Tea');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Lunch: Rajma + Dry Pakoda + Rice + Plain Dal');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Snacks: Kachauri + Coffee');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Mess Schedule > Sunday > Dinner: Chicken Bamboo Shoot + Chicken Curry + Kadhai Paneer + Sweet + Plain Rice + Dal Fry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Cuisine: Mix of North Indian, non-veg heavy (chicken, fish, egg curry). Sunday dinner is the most elaborate with Chicken Bamboo Shoot (local Naga dish).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Note: This is the proposed new mess schedule.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'wifi', 'Wifi > Facts: WiFi is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'wifi', 'Wifi > Facts: LAN is also available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'attendance', 'Attendance > Facts: 75% attendance is mandatory.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Dance club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Music club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Photography club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'clubs', 'Clubs > Facts: Drawing club is available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fests', 'Fests > Facts: Ekarikthin is the college fest.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fests', 'Fests > Facts: Hornbill is another college fest (named after the Hornbill Festival of Nagaland).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', 'Sports > Facts: Cricket, football, volleyball, badminton, and basketball facilities are available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', 'Sports > Facts: Gym is located beside Sholli mess.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', 'Canteen > Facts: South canteen is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', 'Canteen > Facts: No restaurants near campus â€” only delivery services (Swiggy, Zomato) are available.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'laundry', 'Laundry > Facts: No laundry facilities available on campus. Students wash clothes themselves.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: CRS (Class Representative)');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: General Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Culture Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Sports Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Finance Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant General Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Culture Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Sports Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'elections', 'Elections > Roles: Assistant Finance Secretary');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'medical', 'Medical > Facts: Medical facility is available on campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'medical', 'Medical > Facts: Medical timing: 8:30 AM to 4:30 PM.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'transport', 'Transport > Facts: Nearest airport is 14 km from campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'transport', 'Transport > Facts: Nearest railway station is 19 km from campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Dzukou Valley â€” famous valley trek near Kohima.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Kohima War Cemetery â€” World War II memorial.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Tourist: Kisama Heritage Village â€” cultural hub, hosts the Hornbill Festival.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Shopping: No shopping malls near campus.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'nearby_places', 'Nearby Places > Shopping: Nearby shops: Trends, Jack & Jill.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'language_climate', 'Language Climate > Languages: Hindi, English, and Naga languages are spoken.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'language_climate', 'Language Climate > Climate: Cool climate throughout the year.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester: 1st Semester');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Admission Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Grade Card: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Medical Exam Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Alumni Life Membership: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Institute Deposit Refundable: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Library Deposit Refundable: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Degree Certificate Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Convocation Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Id Card Fee: 200');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Training And Placement: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > One Time Fees > Total One Time: 14700');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Tuition Fee: 62500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Computer Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Internet Charges: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Library Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Examination Fee: 1500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Registration Enrolment Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Association And Cultural Fee: 2000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Students Aid Fee: 250');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Sports Center: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Medical And Insurance Fee: 500');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Semester Fees > Total Semester: 72750');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Hostel Admission Fee: 1000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Hostel Deposit Refundable: 3000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > One Time > Total One Time Hostel: 4000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Establishment Charges: 6000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Mess Advance Dining Charges: 21000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Hostel Seat Rent Fan Elec Water: 5000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Hostel Fees > Per Semester > Total Per Semester Hostel: 32000');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Tuition fee is exempted for SC/ST candidates.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Most economically backward students (family income less than Rs 1 lakh per annum) get full remission of tuition fee.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Other economically backward students (family income Rs 1 lakh to Rs 5 lakh per annum) get remission of 2/3rd of tuition fee.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'fee_structure', 'Fee Structure > Notes: Dining charges are adjusted every month on per day basis calculation.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Timetable Note: B.Tech SEM-I for all branches runs from August to December 2025.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1901 Professional English');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1101 Engineering Chemistry');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1102 Engineering Mathematics-I');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CS1201 Introduction to Computer Programming');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CE1201 Engineering Graphics');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: SH1103 Engineering Chemistry Laboratory');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: ME1201 Engineering Workshop');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Courses: CS1202 Computer Programming Laboratory');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Class Timing: Classes run from 8:30 AM to 4:30 PM with breaks.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Groups: Grp-I: CIV, MECH, ECE. Grp-II: CSE, EEE, EIE.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[PHOTO] Classrooms at NIT Nagaland. Interior view of NIT Nagaland classroom with desks and whiteboard');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[PHOTO] Classrooms at NIT Nagaland. Interior view of NIT Nagaland classroom with desks and whiteboard');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen NIT Nagaland. Exterior or entrance view of South canteen');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior - seating area. Green-walled canteen interior with red chairs, ceiling fans, and tables');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen snack counter. Canteen snack and beverage counter with packaged food items on shelves');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior - another angle. Spacious canteen seating area with green walls, ceiling fans, and natural light from windows');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen interior with menu board. Canteen interior showing menu board on wall, Simply South Canteen signage visible');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen food counter with students. Students ordering at the canteen food counter with snacks and drinks display');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[PHOTO] South canteen counter area. Another angle of the canteen counter with students ordering food and green countertops');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] College road/pathway. Road inside NIT Nagaland campus connecting different buildings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[PHOTO] New boys hostel exterior. Exterior view of the new boys hostel building at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[PHOTO] Badminton court. Outdoor badminton court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[PHOTO] Basketball court and sports area. Open basketball court with hoop, buildings and open auditorium structure visible in background');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Parking area with mountain view. Covered parking area with cars, hills and green mountains visible in background showing NIT Nagaland''s scenic location');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - NIT Nagaland. Front view of NIT Nagaland admin block - white 3-storey building with ''National Institute of Technology Nagaland'' signage');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - close up. Close-up view of admin building showing NIT Nagaland name board, modern white building with AC units');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] Admin block - wider angle. Wider angle of NIT Nagaland admin building showing the full facade');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[PHOTO] Bamboo classrooms. Unique bamboo-constructed classroom buildings at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels', '[PHOTO] Hostel building with laundry drying. White 2-storey hostel building surrounded by trees, clothes drying on balcony, hillside location');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[PHOTO] Zanibu girls hostel. Exterior view of Zanibu girls hostel at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', '[PHOTO] Girls mess. Exterior view of girls mess building at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[PHOTO] Patkai girls hostel. Exterior view of Patkai hostel for girls');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[PHOTO] NIT Nagaland main gate. Main entrance gate of NIT Nagaland campus');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 6s] National Institution of Nagaland admin block');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 3s] Admin block area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 7s] Campus area near admin block');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 14s] Campus walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 15s] Shilloi A and B boys hostels exterior walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', '[VIDEO 5s] Patkai A B C and Tiyi mess area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 3s] Open auditorium at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 5s] NIT Nagaland classrooms interior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 7s] Classroom/academic building area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 5s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus grounds');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 8s] Campus surroundings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 30s] Engineering laboratories walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 6s] Laboratory continuation');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 16s] Campus building area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[VIDEO 9s] Basketball court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[VIDEO 4s] South canteen exterior and interior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'canteen', '[VIDEO 3s] Canteen area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 8s] New boys hostel building walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', '[VIDEO 6s] Civil engineering department building');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 2s] Patkai A B C girls hostel exterior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 5s] Girls hostel area');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 9s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'sports', '[VIDEO 4s] Badminton court at NIT Nagaland');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 7s] Zanibu girls hostel exterior walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 9s] Road leading to South canteen');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 7s] College internal road');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 2s] Campus grounds');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_boys', '[VIDEO 5s] Boys hostel building exterior');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 18s] Campus area walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 27s] Campus surroundings and buildings');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 2s] Campus area clip');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'hostels_girls', '[VIDEO 15s] Road to Patkai girls hostel');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 128s] Road to South canteen - full walkthrough');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'campus', '[VIDEO 289s] Full road from college buildings to main gate');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Monday: Breakfast - Bread + Tea. Lunch - Pakoda Sabji + Rice + Plain Dal. Evening Snacks - Samosa + Coffee. Dinner - Egg Curry + Fish Curry + Banana korta + Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Tuesday: Breakfast - Poha + Tea. Lunch - Rajma + Rice + Plain Dal. Evening Snacks - Britannia Cake + Tea. Dinner - Chicken + Seasonal Veg + Plain Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Wednesday: Breakfast - Bread + Tea. Lunch - Nutrela + Chutney + Salad + Rice + Plain Dal. Evening Snacks - Kurkure + Coffee. Dinner - Egg Curry + Paneer Chana + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Thursday: Breakfast - Chowmine + Tea. Lunch - Mixed Veg (Seasonal) + Rice + Plain Dal + Salad. Evening Snacks - Namkeen (Aloo Bhujia / Moong Dal) + Tea. Dinner - Kheer + Chole Bhature + Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Friday: Breakfast - Bread + Tea. Lunch - Rajma + Rice + Plain Dal. Evening Snacks - Dark Fantasy + Coffee. Dinner - Chicken Curry + Seasonal Veg + Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Saturday: Breakfast - Poha + Tea. Lunch - Salad + Mixed Veg + Rice + Plain Dal. Evening Snacks - Lays + Tea. Dinner - Egg Curry + Fish Curry + Malai Korta + Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Sunday: Breakfast - Bread + Tea. Lunch - Rajma + Dry Pakoda + Rice + Plain Dal. Evening Snacks - Kachauri + Coffee. Dinner - Chicken Bamboo Shoote + Chicken Curry + Kadhai Paneer + Sweet + Plain Rice + Dal fry.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'mess', 'Mess > Schedule Notes: NIT Nagaland mess serves non-veg (chicken, fish, egg) multiple days a week. Sunday dinner is the most elaborate with chicken bamboo shoot, kadhai paneer, and sweet.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Timetable: B.Tech SEM-I for All Branches, Aug-Dec 2025. Grp-I: CIV, MECH, ECE. Grp-II: CSE, EEE, EIE.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Timetable Slots: 8:30-9:20, 9:20-10:10, 10:30-11:20, 11:20-12:10, 12:10-1:10 (lunch), 1:10-2:00, 2:00-2:50, 2:50-3:40, 3:40-4:30.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > 1st Sem Courses: SH1901 Professional English, SH1101 Engineering Chemistry, SH1102 Engineering Mathematics-I, CS1201 Introduction to Computer Programming, CE1201 Engineering Graphics, SH1103 Engineering Chemistry Laboratory, ME1201 Engineering Workshop, CS1202 Computer Programming Laboratory.');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Monday Timetable: CS1202 (8:30-10:10), CS1202 (1:10-2:50), CS1202 (2:50-4:30).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Tuesday Timetable: CE1201 (8:30-9:20), SH1901 (9:20-10:10), SH1101 (10:30-11:20), CS1201 G-I (11:20-12:10), SH1102 (1:10-2:00), SH1103/ME1201/CE1201 (2:00-4:30).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Wednesday Timetable: SH1102 (8:30-9:20), SH1901 (9:20-10:10), CS1201 G-II (10:30-12:10), SH1103/ME1201/CE1201 (2:00-4:30).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Thursday Timetable: SH1102 (9:20-10:10), CS1201 G-I (10:30-12:10), SH1103/ME1201/CE1201 (2:00-4:30).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Friday Timetable: CS1201 G-II (8:30-9:20), SH1901 (9:20-10:10), SH1101 (10:30-11:20), SH1103/ME1201/CE1201 (2:00-4:30).');
INSERT INTO knowledge_chunks (college, section, chunk_text) VALUES ('NIT Nagaland', 'academics', 'Academics > Faculty: Dr. Rosaline Jamir & Dr. Wati Walling (Professional English G-2), Dr. Amrit Puzari & Dr. Jhimli Bhattacharyya (Engineering Chemistry G-2), Dr. P.P. Mishra & Dr. Manoj K. Patel (Mathematics G-2), Dr. J. Arul Valan (Computer Programming), Dr. V. Guru Prathap Reddy & Dr. Dhanesh Sing Das (Engineering Graphics), Dr. Shambhu Kumar Mahato & Dr. Amit Kumar Singh (Engineering Workshop).');